---
- name: Display Role Details.
  debug:
    msg:
      - '===================================================================='
      - 'constrict0r.develbase'
      - 'Apply base developer configuration.'
      - '===================================================================='
